// <auto-generated />
namespace Capstone_RPG_Manager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Prova1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Prova1));
        
        string IMigrationMetadata.Id
        {
            get { return "202302021338433_Prova1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
